server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: STUDENT-SERVICE
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/student/**
        - id: SCHOOL-SERVICE
          uri: lb://SCHOOL-SERVICE
          predicates:
            - Path=/school/**, /invoice/**
        - id: LIBRARY-SERVICE
          uri: lb://LIBRARY-SERVICE
          predicates:
            - Path=/api/v1/books/**
        - id: GRADEBOOK-SERVICE
          uri: lb://GRADEBOOK-SERVICE
          predicates:
            - Path=/grade/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost